import { StyleSheet } from 'react-native'
import { mobileTheme } from './index'

const { color, radius, spacing, typography } = mobileTheme

// Transitional layout styles for the existing engineering screens. Each product
// vertical slice can now replace these without changing transport or storage code.
export const screenStyles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: color.canvas },
  container: { flex: 1, gap: spacing.md, justifyContent: 'center', padding: spacing.xl },
  loginContainer: { flexGrow: 1, gap: spacing.lg, justifyContent: 'center', paddingHorizontal: spacing.xl, paddingVertical: spacing.xxl },
  loginHero: { alignSelf: 'center', gap: spacing.sm, maxWidth: 560, width: '100%' },
  loginTitle: { color: color.text, fontSize: typography.title, fontWeight: '700', letterSpacing: 0, lineHeight: 36 },
  loginForm: {
    alignSelf: 'center',
    backgroundColor: color.surface,
    borderColor: color.border,
    borderRadius: radius.lg,
    borderWidth: 1,
    elevation: 2,
    gap: spacing.sm,
    maxWidth: 560,
    padding: spacing.lg,
    shadowColor: color.text,
    shadowOffset: { height: 8, width: 0 },
    shadowOpacity: 0.06,
    shadowRadius: 18,
    width: '100%',
  },
  fieldLabel: { color: color.textSecondary, fontSize: typography.caption, fontWeight: '700', marginBottom: -4 },
  loginFootnote: { color: color.textTertiary, fontSize: typography.caption, lineHeight: 18 },
  debugCard: { gap: spacing.sm, marginTop: spacing.md },
  sessionsContainer: { flex: 1, gap: spacing.sm, paddingHorizontal: spacing.lg, paddingTop: spacing.sm },
  conversationScreen: { flex: 1, minHeight: 0 },
  conversationHeader: { backgroundColor: color.surface, borderBottomColor: color.border, borderBottomWidth: 1, gap: spacing.sm, paddingBottom: spacing.sm, paddingHorizontal: spacing.lg, paddingTop: spacing.sm },
  title: { color: color.text, fontSize: typography.title, fontWeight: '700' },
  subtitle: { color: color.textSecondary, fontSize: typography.body, marginBottom: spacing.sm },
  input: {
    backgroundColor: color.surface,
    borderColor: color.borderStrong,
    borderRadius: radius.md,
    borderWidth: 1,
    color: color.text,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  promptInput: { minHeight: 96, textAlignVertical: 'top' },
  message: { color: color.textSecondary, fontSize: 14, lineHeight: 21 },
  sessionScroll: { marginHorizontal: -spacing.lg },
  sessionList: { gap: spacing.lg, paddingBottom: spacing.xl, paddingHorizontal: spacing.lg, paddingTop: spacing.xs },
  inlineNotice: { gap: spacing.xs },
  bannerAction: { alignSelf: 'flex-start', minHeight: 40, paddingHorizontal: spacing.md },
  directoryLoading: { alignItems: 'center', gap: spacing.sm, paddingVertical: spacing.xxl },
  directorySection: { gap: spacing.sm },
  sectionHeading: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', paddingHorizontal: spacing.xs },
  sectionCount: {
    backgroundColor: color.brandSoft,
    borderRadius: radius.pill,
    color: color.textSecondary,
    fontSize: typography.caption,
    fontWeight: '700',
    minWidth: 24,
    overflow: 'hidden',
    paddingHorizontal: 7,
    paddingVertical: 3,
    textAlign: 'center',
  },
  sessionGroup: { backgroundColor: color.surface, borderColor: color.border, borderRadius: radius.md, borderWidth: 1, elevation: 1, overflow: 'hidden', shadowColor: color.text, shadowOffset: { height: 3, width: 0 }, shadowOpacity: 0.04, shadowRadius: 8 },
  directoryFooter: { gap: spacing.sm, paddingTop: spacing.xs },
  directoryFootnote: { color: color.textTertiary, fontSize: typography.caption, lineHeight: 18, textAlign: 'center' },
  sectionTitle: { color: color.text, fontSize: typography.subheading, fontWeight: '700' },
  sessionTitle: { color: color.text, fontSize: typography.subheading, fontWeight: '600' },
  menuIcon: { color: color.text, fontSize: 22, lineHeight: 24 },
  accountIcon: {
    backgroundColor: color.brand,
    borderRadius: radius.pill,
    color: color.surface,
    fontSize: typography.caption,
    fontWeight: '800',
    minWidth: 32,
    overflow: 'hidden',
    paddingHorizontal: spacing.xs,
    paddingVertical: 7,
    textAlign: 'center',
  },
  settingsIcon: { color: color.text, fontSize: 22, lineHeight: 24 },
  backIcon: { color: color.text, fontSize: 34, lineHeight: 34 },
  statusLine: { alignItems: 'center', backgroundColor: color.surfaceMuted, borderRadius: radius.pill, flexDirection: 'row', gap: spacing.xs, paddingHorizontal: spacing.sm, paddingVertical: spacing.xs },
  settingsScreen: { flex: 1, paddingHorizontal: spacing.lg, paddingTop: spacing.sm },
  settingsContent: { gap: spacing.lg, paddingBottom: spacing.xxl },
  settingsSection: { gap: spacing.xs },
  settingsSectionTitle: {
    color: color.textSecondary,
    fontSize: typography.caption,
    fontWeight: '700',
    paddingHorizontal: spacing.sm,
  },
  settingsGroup: {
    backgroundColor: color.surface,
    borderColor: color.border,
    borderRadius: radius.md,
    borderWidth: 1,
    overflow: 'hidden',
  },
  settingsRow: {
    alignItems: 'center',
    borderBottomColor: color.border,
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    gap: spacing.sm,
    minHeight: 72,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  settingsRowCopy: { flex: 1, gap: spacing.xxs, minWidth: 0 },
  settingsLabel: { color: color.textSecondary, fontSize: typography.caption, fontWeight: '600' },
  settingsValue: { color: color.text, fontSize: typography.body, fontWeight: '600', lineHeight: 21 },
  settingsDetail: { color: color.textTertiary, fontSize: typography.caption, lineHeight: 18 },
})
